AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Relying Party Configuration

#      Tags:
#        Service: Relying Party Configuration
#        Source: govuk-one-login/relying-party-configuration
#        Owner: di-orchestration@digital.cabinet-office.gov.uk

Parameters:
  Environment:
    Type: String
    Description: The name of the environment to deploy to
    AllowedValues:
      - dev
      - build
      - staging
      - integration
      - production
  CodeSigningConfigArn:
    Type: String
    Description: The ARN of the Code Signing Config to use, provided by the deployment pipeline
    Default: none
  PermissionsBoundary:
    Type: String
    Description: The ARN of the permissions boundary to apply when creating IAM roles
    Default: none
  VpcStackName:
    Type: String
    Description: The name of the stack used to create the VPC

Conditions:
  UseCodeSigning: !Not [!Equals [none, !Ref CodeSigningConfigArn]]
  UsePermissionsBoundary: !Not [!Equals [none, !Ref PermissionsBoundary]]
  IsStagingIntOrProd:
    !Or [
      !Equals [staging, !Ref Environment],
      !Equals [integration, !Ref Environment],
      !Equals [production, !Ref Environment],
    ]

Globals:
  Function:
    CodeSigningConfigArn: !If
      - UseCodeSigning
      - !Ref CodeSigningConfigArn
      - !Ref AWS::NoValue
    PermissionsBoundary: !If
      - UsePermissionsBoundary
      - !Ref PermissionsBoundary
      - !Ref AWS::NoValue

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub ${AWS::StackName}-ApiGateway
      StageName: !Sub ${Environment}
      AlwaysDeploy: true
      Tags:
        FMSRegionalPolicy: false
        CustomPolicy: true
      Auth:
        ResourcePolicy:
          CustomStatements:
            - Effect: Allow
              Action: "execute-api:Invoke"
              Principal: "*"
              Resource:
                - "execute-api:/*"
            - Effect: Deny
              Action: "execute-api:Invoke"
              Principal: "*"
              Resource:
                - "execute-api:/*"
              Condition:
                StringNotEquals:
                  aws:SourceVpce:
                    - Fn::ImportValue: !Sub "${VpcStackName}-ExecuteApiGatewayEndpointId"
      EndpointConfiguration:
        Type: PRIVATE
        VpcEndpointIds:
          - Fn::ImportValue: !Sub "${VpcStackName}-ExecuteApiGatewayEndpointId"

  TempLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: temp-api.handler
      Runtime: nodejs20.x
      Architectures:
        - arm64
      Events:
        Get:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /temp-api
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - src/temp-api.ts
        Minify: true
        Sourcemap: true
        Target: es2022
        UseNpmCi: True

  #region ClientRegistry DynamoDB Table
  ClientRegistryTableEncryptionKey:
    Type: AWS::KMS::Key
    Properties:
      Description: KMS encryption key for Orchestration Client Registry DynamoDB table
      EnableKeyRotation: true
      KeyPolicy:
        Version: 2012-10-17
        Statement:
          - Sid: AllowIamManagement
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: kms:*
            Resource: "*"
          - Sid: AllowDynamodbAccessToEncryptionKey
            Effect: Allow
            Principal:
              Service: dynamodb.amazonaws.com
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:DescribeKey
            Resource: "*"
            Condition:
              ArnLike:
                kms:EncryptionContext:aws:dynamodb:table/arn: !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/*

  ClientRegistryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${Environment}-client-registry
      AttributeDefinitions:
        - AttributeName: ClientID
          AttributeType: S
        - AttributeName: ClientName
          AttributeType: S
      KeySchema:
        - AttributeName: ClientID
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: ClientNameIndex
          KeySchema:
            - AttributeName: ClientName
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
        KMSMasterKeyId: !GetAtt ClientRegistryTableEncryptionKey.Arn
        SSEType: KMS
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      DeletionProtectionEnabled: true
      Tags:
        - Key: Name
          Value: ClientRegistryTable
        - !If
          - IsStagingIntOrProd
          - Key: BackupFrequency
            Value: Bihourly
          - !Ref AWS::NoValue

  #endregion
