name: Deploy API Dev

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  security-events: write
  actions: read

jobs:
  unit-tests:
    uses: ./.github/workflows/unit-tests.yml

  integration-tests:
    uses: ./.github/workflows/integration-tests.yml

  sonarcloud:
    uses: ./.github/workflows/sonarcloud.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  terraform-checks:
    uses: ./.github/workflows/terraform-checks.yml

  checkov:
    uses: ./.github/workflows/checkov.yml

  validation:
    uses: ./.github/workflows/validation.yml
    secrets:
      SAM_VALIDATE_ROLE_ARN: ${{ secrets.DEV_SAM_VALIDATE_ROLE_ARN }}

  deploy-api-dev:
    uses: ./.github/workflows/deploy-api.yml
    needs:
      - unit-tests
      - integration-tests
      - sonarcloud
      - terraform-checks
      - checkov
      - validation
    secrets:
      GH_ACTIONS_ROLE_ARN: ${{ secrets.DEV_GH_ACTIONS_ROLE_ARN }}
      ARTIFACT_BUCKET_NAME: ${{ secrets.DEV_ARTIFACT_BUCKET_NAME }}
      SIGNING_PROFILE_NAME: ${{ secrets.DEV_SIGNING_PROFILE_NAME }}
      CONTAINER_SIGN_KMS_KEY: ${{ secrets.DEV_CONTAINER_SIGN_KMS_KEY }}
      ECR_REPOSITORY: ${{ secrets.DEV_TEST_ECR_REPOSITORY }}
