name: Validation

on:
  workflow_call:
    secrets:
      SAM_VALIDATE_ROLE_ARN:
        required: true

jobs:
  style-checks:
    name: Validation Checks
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out repository code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Node
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm ci

      - name: Check ESLint and Prettier
        run: npm run lint

      - name: Set up tflint
        uses: terraform-linters/setup-tflint@4cb9feea73331a35b422df102992a03a44a3bb33

      - name: Lint Terraform
        run: npm run tflint

      - name: Setup SAM
        uses: aws-actions/setup-sam@d78e1a4a9656d3b223e59b80676a797f20093133 # v2
        with:
          use-installer: true

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5.1.1
        with:
          role-to-assume: ${{ secrets.SAM_VALIDATE_ROLE_ARN }}
          aws-region: eu-west-2

      - name: Run SAM validate + cfnlint
        run: sam validate -t template.yml --region eu-west-2 --lint

  detect-secrets:
    name: Detect Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.11.2"

      - name: Run detect-secrets
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
        with:
          extra_args: "detect-secrets --all-files"
