name: Validation

on:
  workflow_call:
    secrets:
      SAM_VALIDATE_ROLE_ARN:
        required: true

jobs:
  style-checks:
    name: Validation Checks
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out repository code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm ci

      - name: Check ESLint and Prettier
        run: npm run lint

      - name: Set up tflint
        uses: terraform-linters/setup-tflint@6e1e0642c0289bd619021bf6b34e3c08ed1e005a

      - name: Lint Terraform
        run: npm run tflint

      - name: Setup SAM
        if: github.actor != 'dependabot[bot]'
        uses: aws-actions/setup-sam@89ddb14d60e682855e3fea4be85b3c56485de310 # v3
        with:
          use-installer: true

      - name: Set up AWS credentials
        if: github.actor != 'dependabot[bot]'
        uses: aws-actions/configure-aws-credentials@e6de054238d6b7531b4efff3b6587d9aade6a06c # v6.2.3
        with:
          role-to-assume: ${{ secrets.SAM_VALIDATE_ROLE_ARN }}
          aws-region: eu-west-2

      - name: Run SAM validate + cfnlint
        if: github.actor != 'dependabot[bot]'
        run: sam validate -t template.yml --region eu-west-2 --lint

  detect-secrets:
    name: Detect Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.11.2"

      - name: Run detect-secrets
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
        with:
          extra_args: "detect-secrets --all-files"
